spring:
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
#   Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2? ?????.
    url: jdbc:h2:mem:devblog # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username ?? (??? ??? ??)
    password:  # H2 ?? ? ??? password ?? (??? ??? ??)

  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ?? 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # ???? query? ???

logging.level:
  org.hibernate.SQL: debug